services:
  crazyswarm-rmf:
    build: 
      context: ./
      target: crazyswarm-rmf
    container_name: crazyswarm-rmf
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - ./crazyflie-firmware:/root/crazyflie-firmware
      - ./cswarm_ws:/root/cswarm_ws
      - ./rmf_ws:/root/rmf_ws
    devices:
      - /dev/input:/dev/input
      - /dev/dri:/dev/dri
    network_mode: "host"
